# Generated by Django 3.1.2 on 2020-10-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201020_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
    ]
