# Generated by Django 3.1.2 on 2020-10-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_chartproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChartProduct',
            new_name='CartProduct',
        ),
    ]
