# Generated by Django 3.1.2 on 2020-10-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20201020_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
