# Generated by Django 3.1.2 on 2020-10-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_cartproduct_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_description',
        ),
        migrations.AddField(
            model_name='product',
            name='price_integer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
