# Generated by Django 3.1.2 on 2020-10-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20201022_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_integer',
            field=models.FloatField(default=0),
        ),
    ]
