# Generated by Django 3.1.2 on 2020-10-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20201022_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_integer',
            new_name='price_float',
        ),
    ]
